spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movie/**
          filters:
            - StripPrefix=2
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
